name: Events Demo 1
on:
  pull_request:
    types:
      - opened
    branches:
      -  main
  workflow_dispatch:
  push:
    branches:
      -  main
    paths-ignore:
      - '.gitignore/workflows/* '
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Test code
        run: yarn test
      - name: Build code
        run: yarn build
      - name: Deploy project
        run: echo "Deploying..."